name: tilecache_calc
description: Library for tile cache calculations
version: 0.0.1
author: Anders Scisly Sagevik <anders@discoos.org>
homepage: https://github.com/DISCOOS/tilecache-calc

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  latlong2: ^0.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
